status-page-containerization-main/status-page-containerization-main/statuspage/extras/api/urls.py
from statuspage.api.routers import StatusPageRouter
from . import views


router = StatusPageRouter()
router.APIRootView = views.ExtrasRootView

# Webhooks
router.register('webhooks', views.WebhookViewSet)

# Change logging
router.register('object-changes', views.ObjectChangeViewSet)

# ContentTypes
router.register('content-types', views.ContentTypeViewSet)

app_name = 'extras-api'
urlpatterns = router.urls

status-page-containerization-main/status-page-containerization-main/statuspage/extras/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls

from . import views # noqa Required for registration

app_name = 'extras'
urlpatterns = [
    path('changelog/', include(get_model_urls('extras', 'objectchange'))),
    path('webhooks/', include(get_model_urls('extras', 'webhook'))),
]

status-page-containerization-main/status-page-containerization-main/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView, \
    SubscriberManageWebhookListView, SubscriberManageWebhookCreateView, SubscriberManageWebhookDeleteView, \
    SubscriberManageWebhookEditView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/manage/webhooks', SubscriberManageWebhookListView.as_view(), name='subscriber_manage_webhook_list'),
    path('subscribers/<str:management_key>/manage/webhooks/create', SubscriberManageWebhookCreateView.as_view(), name='subscriber_manage_webhook_create'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/edit', SubscriberManageWebhookEditView.as_view(), name='subscriber_manage_webhook_edit'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/delete', SubscriberManageWebhookDeleteView.as_view(), name='subscriber_manage_webhook_delete'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

status-page-containerization-main/status-page-containerization-main/statuspage/users/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views

app_name = 'users'
urlpatterns = [
    # User
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),

    # API Tokens
    path('api-tokens/', include(get_model_urls('users', 'token'))),

    # Two-Factor devices
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

status-page-containerization-main/status-page-containerization-main/statuspage/extras/models/change_logging.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse

from extras.choices import *
from utilities.querysets import RestrictedQuerySet


class ObjectChange(models.Model):
    """
    Record a change to an object and the user account associated with that change. A change record may optionally
    indicate an object related to the one being changed. For example, a change to an interface may also indicate the
    parent device. This will ensure changes made to component models appear in the parent model's changelog.
    """
    time = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        db_index=True
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        related_name='changes',
        blank=True,
        null=True
    )
    user_name = models.CharField(
        max_length=150,
        editable=False
    )
    request_id = models.UUIDField(
        editable=False
    )
    action = models.CharField(
        max_length=50,
        choices=ObjectChangeActionChoices
    )
    changed_object_type = models.ForeignKey(
        to=ContentType,
        on_delete=models.PROTECT,
        related_name='+'
    )
    changed_object_id = models.PositiveBigIntegerField()
    changed_object = GenericForeignKey(
        ct_field='changed_object_type',
        fk_field='changed_object_id'
    )
    related_object_type = models.ForeignKey(
        to=ContentType,
        on_delete=models.PROTECT,
        related_name='+',
        blank=True,
        null=True
    )
    related_object_id = models.PositiveBigIntegerField(
        blank=True,
        null=True
    )
    related_object = GenericForeignKey(
        ct_field='related_object_type',
        fk_field='related_object_id'
    )
    object_repr = models.CharField(
        max_length=200,
        editable=False
    )
    prechange_data = models.JSONField(
        editable=False,
        blank=True,
        null=True
    )
    postchange_data = models.JSONField(
        editable=False,
        blank=True,
        null=True
    )

    objects = RestrictedQuerySet.as_manager()

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return '{} {} {} by {}'.format(
            self.changed_object_type,
            self.object_repr,
            self.get_action_display().lower(),
            self.user_name
        )

    def save(self, *args, **kwargs):

        # Record the user's name and the object's representation as static strings
        if not self.user_name:
            self.user_name = self.user.username
        if not self.object_repr:
            self.object_repr = str(self.changed_object)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('extras:objectchange', args=[self.pk])

    def get_action_color(self):
        return ObjectChangeActionChoices.colors.get(self.action)

status-page-containerization-main/status-page-containerization-main/statuspage/extras/models/models.py
import json

from django.conf import settings
from django.contrib import admin
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from rest_framework.utils.encoders import JSONEncoder

from extras.choices import WebhookHttpMethodChoices
from extras.conditions import ConditionSet
from extras.constants import HTTP_CONTENT_TYPE_JSON
from extras.utils import FeatureQuery
from statuspage.models import ChangeLoggedModel

__all__ = (
    'Webhook',
    'ConfigRevision',
)

from subscribers.models import Subscriber

from utilities.utils import render_jinja2


class Webhook(ChangeLoggedModel):
    """
    A Webhook defines a request that will be sent to a remote application when an object is created, updated, and/or
    delete in NetBox. The request will contain a representation of the object, which the remote application can act on.
    Each Webhook can be limited to firing only on certain actions or certain object types.
    """
    content_types = models.ManyToManyField(
        to=ContentType,
        related_name='webhooks',
        verbose_name='Object types',
        limit_choices_to=FeatureQuery('webhooks'),
        help_text=_("The object(s) to which this Webhook applies.")
    )
    name = models.CharField(
        max_length=150,
        unique=True
    )
    subscriber = models.ForeignKey(
        to=Subscriber,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='webhooks',
    )
    type_create = models.BooleanField(
        default=False,
        help_text=_("Triggers when a matching object is created.")
    )
    type_update = models.BooleanField(
        default=False,
        help_text=_("Triggers when a matching object is updated.")
    )
    type_delete = models.BooleanField(
        default=False,
        help_text=_("Triggers when a matching object is deleted.")
    )
    payload_url = models.CharField(
        max_length=500,
        verbose_name='URL',
        help_text=_('This URL will be called using the HTTP method defined when the webhook is called. '
                    'Jinja2 template processing is supported with the same context as the request body.')
    )
    enabled = models.BooleanField(
        default=True
    )
    http_method = models.CharField(
        max_length=30,
        choices=WebhookHttpMethodChoices,
        default=WebhookHttpMethodChoices.METHOD_POST,
        verbose_name='HTTP method'
    )
    http_content_type = models.CharField(
        max_length=100,
        default=HTTP_CONTENT_TYPE_JSON,
        verbose_name='HTTP content type',
        help_text=_('The complete list of official content types is available '
                    '<a href="https://www.iana.org/assignments/media-types/media-types.xhtml">here</a>.')
    )
    additional_headers = models.TextField(
        blank=True,
        help_text=_("User-supplied HTTP headers to be sent with the request in addition to the HTTP content type. "
                    "Headers should be defined in the format <code>Name: Value</code>. Jinja2 template processing is "
                    "supported with the same context as the request body (below).")
    )
    body_template = models.TextField(
        blank=True,
        help_text=_('Jinja2 template for a custom request body. If blank, a JSON object representing the change will be'
                    ' included. Available context data includes: <code>event</code>, <code>model</code>, '
                    '<code>timestamp</code>, <code>username</code>, <code>request_id</code>, and <code>data</code>.')
    )
    secret = models.CharField(
        max_length=255,
        blank=True,
        help_text=_("When provided, the request will include a 'X-Hook-Signature' "
                    "header containing a HMAC hex digest of the payload body using "
                    "the secret as the key. The secret is not transmitted in "
                    "the request.")
    )
    conditions = models.JSONField(
        blank=True,
        null=True,
        help_text=_("A set of conditions which determine whether the webhook will be generated.")
    )
    ssl_verification = models.BooleanField(
        default=True,
        verbose_name='SSL verification',
        help_text=_("Enable SSL certificate verification. Disable with caution!")
    )
    ca_file_path = models.CharField(
        max_length=4096,
        null=True,
        blank=True,
        verbose_name='CA File Path',
        help_text=_('The specific CA certificate file to use for SSL verification. '
                    'Leave blank to use the system defaults.')
    )

    class Meta:
        ordering = ('name',)
        constraints = (
            models.UniqueConstraint(
                fields=('payload_url', 'type_create', 'type_update', 'type_delete'),
                name='%(app_label)s_%(class)s_unique_payload_url_types'
            ),
        )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('extras:webhook', args=[self.pk])

    @property
    def docs_url(self):
        return f'{settings.STATIC_URL}docs/models/extras/webhook/'

    def clean(self):
        super().clean()

        # At least one action type must be selected
        if not any([
            self.type_create, self.type_update, self.type_delete
        ]):
            raise ValidationError(
                "At least one event type must be selected: create, update and/or delete."
            )

        if self.conditions:
            try:
                ConditionSet(self.conditions)
            except ValueError as e:
                raise ValidationError({'conditions': e})

        # CA file path requires SSL verification enabled
        if not self.ssl_verification and self.ca_file_path:
            raise ValidationError({
                'ca_file_path': 'Do not specify a CA certificate file if SSL verification is disabled.'
            })

    def render_headers(self, context):
        """
        Render additional_headers and return a dict of Header: Value pairs.
        """
        if not self.additional_headers:
            return {}
        ret = {}
        data = render_jinja2(self.additional_headers, context)
        for line in data.splitlines():
            header, value = line.split(':', 1)
            ret[header.strip()] = value.strip()
        return ret

    def render_body(self, context):
        """
        Render the body template, if defined. Otherwise, jump the context as a JSON object.
        """
        if self.body_template:
            return render_jinja2(self.body_template, context)
        else:
            return json.dumps(context, cls=JSONEncoder)

    def render_payload_url(self, context):
        """
        Render the payload URL.
        """
        return render_jinja2(self.payload_url, context)


class ConfigRevision(models.Model):
    """
    An atomic revision of Status-Page's configuration.
    """
    created = models.DateTimeField(
        auto_now_add=True
    )
    comment = models.CharField(
        max_length=200,
        blank=True
    )
    data = models.JSONField(
        blank=True,
        null=True,
        verbose_name='Configuration data'
    )

    def __str__(self):
        return f'Config revision #{self.pk} ({self.created})'

    def __getattr__(self, item):
        if item in self.data:
            return self.data[item]
        return super().__getattribute__(item)

    def activate(self):
        """
        Cache the configuration data.
        """
        cache.set('config', self.data, None)
        cache.set('config_version', self.pk, None)

    @admin.display(boolean=True)
    def is_active(self):
        return cache.get('config_version') == self.pk

status-page-containerization-main/status-page-containerization-main/statuspage/templates/extras/object_changelog.html
{% extends base_template %}
{% load render_table from django_tables2 %}

{% block title %}{{ object }}: Changelog{% endblock %}

{% block dashboard_content %}
  <div class="row mb-3">
    <div class="col col-md-12">
      <div class="card">
        <div class="card-body table-responsive">
          {% render_table table 'inc/table.html' %}
          {% include 'inc/paginator.html' with paginator=table.paginator page=table.page rounded='md:rounded-b-lg' %}
        </div>
      </div>
      <div class="text-gray-500">
        Change log retention: {% if config.CHANGELOG_RETENTION %}{{ config.CHANGELOG_RETENTION }} days{% else %}Indefinite{% endif %}
      </div>
    </div>
  </div>
{% endblock %}

status-page-containerization-main/status-page-containerization-main/statuspage/templates/extras/objectchange.html
{% extends 'base/dashboard.html' %}
{% load helpers %}

{% block title %}{{ object }}{% endblock %}

{% block dashboard_content %}
  <div class="grid grid-cols-2 gap-4 mb-3">
    <div class="bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
      <div class="text-2xl">
        Change
      </div>
      <div class="px-4">
        <table class="text-left w-full">
          <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
            <tr>
              <th scope="row">Time</th>
              <td>
                {{ object.time|annotated_date }}
              </td>
            </tr>
            <tr>
              <th scope="row">User</th>
              <td>
                {% if object.user.get_full_name %}
                {{ object.user.get_full_name }} ({{ object.user_name }})
                {% else %}
                {{ object.user_name }}
                {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Action</th>
              <td>
                {{ object.get_action_display }}
              </td>
            </tr>
            <tr>
              <th scope="row">Object Type</th>
              <td>
                {{ object.changed_object_type }}
              </td>
            </tr>
            <tr>
              <th scope="row">Object</th>
              <td>
                {% if object.changed_object and object.changed_object.get_absolute_url %}
                {{ object.changed_object|linkify }}
                {% else %}
                {{ object.object_repr }}
                {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Request Id</th>
              <td>
                {{ object.request_id }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
      <div class="flex flex-row justify-between">
        <div class="text-2xl">Difference</div>
        <div class="flex flex-row print:hidden">
          <a {% if prev_change %}href="{% url 'extras:objectchange' pk=prev_change.pk %}"{% else %}disabled{% endif %} class="border border-gray-500 hover:bg-gray-500 hover:text-white text-gray-500 px-2 py-1 rounded-l-md font-medium h-8 flex items-center">
            <i class="mdi mdi-chevron-left" aria-hidden="true"></i> Previous
          </a>
          <a {% if next_change %}href="{% url 'extras:objectchange' pk=next_change.pk %}"{% else %}disabled{% endif %} class="border border-gray-500 hover:bg-gray-500 hover:text-white text-gray-500 px-2 py-1 rounded-r-md font-medium h-8 flex items-center">
            Next <i class="mdi mdi-chevron-right" aria-hidden="true"></i>
          </a>
        </div>
      </div>
      <div class="space-y-2">
        {% if diff_added == diff_removed %}
        <span class="text-gray-400" style="margin-left: 10px;">
                          {% if object.action == 'create' %}
                              Object Created
                          {% elif object.action == 'delete' %}
                              Object Deleted
                          {% else %}
                              No Changes
                          {% endif %}
                      </span>
        {% else %}
        <pre class="change-diff change-removed">{{ diff_removed|json }}</pre>
        <pre class="change-diff change-added">{{ diff_added|json }}</pre>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="grid grid-cols-2 gap-4 mb-3">
    <div class="bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
      <div class="text-2xl">
        Pre-Change Data
      </div>
      <div>
        {% if object.prechange_data %}
        <pre class="change-data">{% for k, v in object.prechange_data.items %}{% spaceless %}
                      <span{% if k in diff_removed %} class="removed"{% endif %}>{{ k }}: {{ v|json }}</span>
          {% endspaceless %}{% endfor %}
                  </pre>
        {% elif non_atomic_change %}
        Warning: Comparing non-atomic change to previous change record (<a href="{% url 'extras:objectchange' pk=prev_change.pk %}">{{ prev_change.pk }}</a>)
        {% else %}
        <span class="text-gray-400">None</span>
        {% endif %}
      </div>
    </div>
    <div class="bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
      <div class="text-2xl">
        Post-Change Data
      </div>
      <div>
        {% if object.postchange_data %}
        <pre class="change-data">{% for k, v in object.postchange_data.items %}{% spaceless %}
                          <span{% if k in diff_added %} class="added"{% endif %}>{{ k }}: {{ v|json }}</span>
          {% endspaceless %}{% endfor %}
                      </pre>
        {% else %}
        <span class="text-gray-400">None</span>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="space-y-2">
    {% include 'inc/panel_table.html' with table=related_changes_table heading='Related Changes' %}
    {% if related_changes_count > related_changes_table.rows|length %}
    <div class="text-end">
      <a href="{% url 'extras:objectchange_list' %}?request_id={{ object.request_id }}" class="btn btn-primary">See All {{ related_changes_count|add:"1" }} Changes</a>
    </div>
    {% endif %}
  </div>
{% endblock %}

status-page-containerization-main/status-page-containerization-main/statuspage/templates/extras/objectchange_list.html
{% extends 'generic/object_list.html' %}

{% block title %}Change Log{% endblock %}

{% block dashboard_content %}
  {{ block.super }}
  <div class="text-gray-400 px-3">
    Change log retention: {% if config.CHANGELOG_RETENTION %}{{ config.CHANGELOG_RETENTION }} days{% else %}Indefinite{% endif %}
  </div>
{% endblock %}

status-page-containerization-main/status-page-containerization-main/statuspage/templates/extras/webhook.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Webhook</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Enabled</th>
            <td>{% checkmark object.enabled %}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Events</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Create</th>
            <td>{% checkmark object.type_create %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Update</th>
            <td>{% checkmark object.type_update %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Delete</th>
            <td>{% checkmark object.type_delete %}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">HTTP Request</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">HTTP Method</th>
            <td>{{ object.get_http_method_display }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Payload URL</th>
            <td class="font-mono">{{ object.payload_url }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">HTTP Content Type</th>
            <td>{{ object.http_content_type }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Secret</th>
            <td>{{ object.secret|placeholder }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">SSL</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">SSL Verification</th>
            <td>{% checkmark object.ssl_verification %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">CA File Path</th>
            <td>{{ object.ca_file_path|placeholder }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_right %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Assigned Models</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          {% for ct in object.content_types.all %}
            <tr>
              <td>{{ ct }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Conditions</div>
    <div class="px-4">
      {% if object.conditions %}
        <pre>{{ object.conditions|json }}</pre>
      {% else %}
        <span class="text-muted">None</span>
      {% endif %}
    </div>
  </div>
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Additional Headers</div>
    <div class="px-4">
      {% if object.additional_headers %}
        <pre>{{ object.additional_headers }}</pre>
      {% else %}
        <span class="text-muted">None</span>
      {% endif %}
    </div>
  </div>
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Body Template</div>
    <div class="px-4">
      {% if object.body_template %}
        <pre>{{ object.body_template }}</pre>
      {% else %}
        <span class="text-muted">None</span>
      {% endif %}
    </div>
  </div>
{% endblock %}